### ISSUE TITLE
Link between backend and Revealjs / js/ css

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor-reveal.js#1]
This is an excellent idea to move to a separate project the asciidoctor backend of revealjs. Nevertheless, there is still an issue as there is no link between the version supported of revealjs and this backend.

I know that the purpose of this repo is not at all to maintain what revealjs did but that should be easier for our users that there is a git submodule mapped to a tag version of this backend or something else (bower, ruby-bower, ...).

This is what I have done with hyla project where revealjs is embedded (css, js) - https://github.com/cmoulliard/hyla/tree/master/lib/resources/revealjs and where there is a command that the user can use to create a project for a slideshow, .... including also a config.yaml file with parameters (https://github.com/cmoulliard/hyla/blob/master/documentation/scripts/generate_slideshow_revealjs_config.sh)

**Comment by obilodeau** [comment]
I just left a comment in #10 that is strongly related to this issue. I suggest you go and read it and let me know what you think.

**Comment by mojavelinux** [comment]
Since #10 is now closed, perhaps it's best to continue the conversation in this issue since it deals directly with the problem at hand.

**Comment by obilodeau** [comment]
I see two use-cases defended here: 
* slides that are located inside an open source project and that should be maintained over time
* slides used in a presentation and that are frozen and in an archival state

I mostly deal with the latter type of slide decks. So I'll talk about that use case. We've patched reveal.js so that the speaker notes plugin output nicer notes and we've added a theme. The theme is branded so it won't be sent upstream and the notes patch was done in a hurry and can be seen as a hack. Additionally we used an unreleased asciidoctor back-end (before the -reveal.js repo) and we rendered our slides before some of our patches were merged.

For our presentation sources repo, we used git submodules to our own forks (both asciidoctor-reveal.js and revealjs) and created a Makefile that would build our slides. For [our public slides repo](https://github.com/eset/slides) we can pin specific version of the specific reveal.js back-end we used using git submodules again. This has the benefit that github pages does the right thing (tm) IOW it pulls the exact version of reveal.js we require and we can host slides there with a very lightweight repo.

I would like to hear how that could be achieved using Bower. Git submodules are not easy to use if you are not familiar with git.

**Comment by cmoulliard** [comment]
You could also use Hyla project (
https://github.com/cmoulliard/hyla/blob/master/documentation/introduction.adoc#6-generate-a-slideshow)
as it supports natively Revealjs without the need to use bower, ...

On Tue, Mar 10, 2015 at 5:14 AM, Olivier Bilodeau <notifications@github.com>
wrote:

> I see two use-cases defended here:
>
>    - slides that are located inside an open source project and that
>    should be maintained over time
>    - slides used in a presentation and that are frozen and in an archival
>    state
>
> I mostly deal with the latter type of slide decks. So I'll talk about that
> use case. We've patched reveal.js so that the speaker notes plugin output
> nicer notes and we've added a theme. The theme is branded so it won't be
> sent upstream and the notes patch was done in a hurry and can be seen as a
> hack. Additionally we used an unreleased asciidoctor back-end (before the
> -reveal.js repo) and we rendered our slides before some of our patches were
> merged.
>
> For our presentation sources repo, we used git submodules to our own forks
> (both asciidoctor-reveal.js and revealjs) and created a Makefile that would
> build our slides. For our public slides repo
> <https://github.com/eset/slides> we can pin specific version of the
> specific reveal.js back-end we used using git submodules again. This has
> the benefit that github pages does the right thing (tm) IOW it pulls the
> exact version of reveal.js we require and we can host slides there with a
> very lightweight repo.
>
> I would like to hear how that could be achieved using Bower. Git
> submodules are not easy to use if you are not familiar with git.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-reveal.js/issues/1#issuecomment-77993212>
> .
>



-- 
Charles Moulliard
Apache Committer / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by mojavelinux** [comment]
> I would like to hear how that could be achieved using Bower. Git submodules are not easy to use if you are not familiar with git.

To clarify, the goal here is to switch to proper packaging. Bower will grab the web assets, such as JavaScript and CSS, by downloading a specific release of reveal.js. To get the Asciidoctor backend, we should be publishing this backend as a gem so it can be installed just like Asciidoctor. Ideally, for a stable presentation, everything should be based on releases.

The reason we aren't there yet is because this repository is only just emerging from a prototype state. Therefore, up to this point, there hasn't been any perception of stability :) But we're heading there.

**Comment by mojavelinux** [comment]
Of course, Hyla can take the same approach, but also offer a management abstraction over the whole thing.

**Comment by obilodeau** [comment]
How will a custom revealjs theme be handled? With revealjs 2.x you needed
to fork, add your own .sass file and build.

This implies that you need to fork revealjs and point bower to your fork.
At this point a non-rubyist like me is going to do git submodules anyway..

I realize this is probably a revealjs problem. They are probably unaware of
our use case. Reveal.js is mostly forked (or downloaded) then modified in
place whereas we try to link to it.

**Comment by mojavelinux** [comment]
I would probably then just change the path to the revealjs theme, separate from reveal. That might give you two copies of reveal, one that is the foundation and one where you modify the themes. In that case, though, the gitsubmodule is part of your slides project.

The important thing is that the reveal.js backend is documenting which reveal.js release it is designed to use. So even if you don't use bower, the information is still in the metadata.

**Comment by cmoulliard** [comment]
This is why and even if the solution isn't perfect I have packaged in a gem (= hyla project) the asciidoctor backends (revealjs) and the revealjs project (2.x, soon 3.x) as managing stuffs like that for a deployment using git submodule or bower is also not so easy for technical & non technical guys

**Comment by mojavelinux** [comment]
I sorted out how make templates behave like a normal converter. See https://github.com/asciidoctor/asciidoctor-bespoke.js/blob/master/lib/asciidoctor-bespoke/converter.rb. You can then hide the use of the templates and allow the user to use:

    $ asciidoctor -r asciidoctor-reveal -b reveal slides.adoc

The benefits are:

1. you can distribute and install as a RubyGem
2. the basebackend and htmlsyntax is set correctly (as html)
3. you can control the options

I think this is useful even for integrations like hyla. It hides the use of the templates, but still allows the user to supply extra templates to customize the output.

**Comment by obilodeau** [comment]
I'm thinking of closing this issue and opening a new one more focused since a lot of things have changed and best practices have emerged. Thoughts?

However,

> I would probably then just change the path to the revealjs theme, separate from reveal.

Problem is you need a full reveal.js install in order to compile the theme's css from its scss file.

**Comment by Mogztter** [comment]
> I'm thinking of closing this issue and opening a new one more focused since a lot of things have changed and best practices have emerged. Thoughts?

Yes 💯
