### ISSUE TITLE
Migrate jade templates to pug

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-reveal.js#102]
The Jade project has been renamed to Pug. Therefore, the Jade templates should be migrated. This issue is a reminder to perform that migration.

This is simply a name change. In my experience, the only steps required are:
1. change file extension from .jade to .pug
2. switch from the jade module to the pug module

Since we don't yet declare the module dependency in this project, this should just be matter of changing the file extension and switching the development environment.

This could happen as part of #95.

**Comment by obilodeau** [comment]
As stated elsewhere, pug is still in beta, as of now it is in beta6 (https://github.com/pugjs/pug/releases), and there are breaking changes in there: https://pugjs.org/api/migration-v2.html

Since our javascript story is pretty recent, I don't think we should necessary hold off the migration. We should just be aware that the road ahead might be bumpy.

**Comment by mojavelinux** [comment]
Oh, wow. Thanks for pointing that out. I didn't realize pug didn't have an official first release yet. I was under the impression that when they changed the name, they had made a stable release. The warning messages coming from various plugins that jade is deprecated then seem to be premature.

...for our purposes, the beta is fine since our whole pug-based template infrastructure is beta anyway.

**Comment by obilodeau** [comment]
This is no longer valid since we are now compiling slim templates to pure ruby before conversion to javascript. This is now in master and will be released in upcoming 1.1.0.
