### ISSUE TITLE
Discuss: versioning scheme and releases

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#109]
cc @Mogztter @mojavelinux 

I decided to poke you here since twitter, gitter and discuss felt like less good options. Feel free to ask me to readjust.

I'm about to go into intense finish research/presentation preparation mode in the next two months and I won't be doing my daily routine work on asciidoctor-revealjs for a while. Since we merged node (npm) and ruby (bundler) major 'workflow affecting' features (and a bunch of improvements beforehand) I think we are due for a release.

I suggest to tag this our first release and move all milestone 1.0 issues to our next release since I won't have time to do it and I don't want to delay a release.

Now this brings us into the versioning question. I've noticed that most asciidoctor projects align on the release version of asciidoctor. Do we need or want that? I'm not against it but since we move at a different pace, I think we should be independent and I suggest we call this next version 1.0.0. I know the bespoke back-end does it.

If we agree, I'll retarget the remaining 1.0 milestone issues to 1.1(.0) and provide our first changelog.

**Comment by Mogztter** [comment]
I've similar issues with the current versioning scheme in Asciidoctor.js 😞 

This is what I've wrote on the mailing list (one year ago): http://discuss.asciidoctor.org/Projects-versioning-strategy-td3841.html

As mentioned in my post, I do think that the Asciidoctor core version is an essential information but I also think we should embrace semantic versioning.
"build metadata" could be an interesting solution otherwise we would most likely end up with a compatibility matrix on each project:

|Project version|Asciidoctor version|
------------ | -------------
|1.x | 1.5.4|
|2.x | 1.5.5|
|master|1.6.x|

(Maybe it's not that bad)

The versioning on the Chrome extension (ie. Core plus fourth number versioning) is kind of OK but has some limitations.

Anyway if you ask me to choose, I will go with semantic versioning and use "build metadata" where I can (or a compatibility matrix to make it clear that project version Y is using Asciidoctor version X).
If we decide to go that way, one thing we should take care of is how to make the transition as smoothly as possible ? from 1.5.4 to 2.0.0 ? Since we can't use 1.0.0 anymore (at least for AsciidoctorJ and Asciidoctor.js)

**Comment by mojavelinux** [comment]
I'm a little late to the party here, but :+1: to doing the release.

I agree the version of asciidoctor-reveal.js should start at 1.0.0. Here's my general thinking around this. If the module provides core (Asciidoctor, Asciidoctor.js, AsciidoctorJ), or it is a tightly integrated extension of core (Asciidoctor PDF), then it should align with the version number of core because it's part of the same offering. On the other hand, if a component uses core, but can otherwise work with a range of core versions, then it should have its own versioning.

When we do introduce new discrete components, then we should definitely follow the semantic versioning model. So :+1: to @Mogztter proposal.

**Comment by mojavelinux** [comment]
(I'm a little torn how to handle the versions for the plugins, but that's a separate conversation).

**Comment by obilodeau** [comment]
Thanks for your comments! Moving forward with the 1.0.0 plan.

**Comment by obilodeau** [comment]
May I add: since the usual way to use asciidoctor-reveal.js to render slides should be through bundler, asciidoctor version requirement will be enforced by the gemspec anyway so compatibility matrices are not that useful.

**Comment by mojavelinux** [comment]
Great point. I recommend either:

```
s.add_runtime_dependency 'asciidoctor', '>= 1.5.0'
```

or

```
s.add_runtime_dependency 'asciidoctor', '~> 1.5.0'
```

The second prevents use of Asciidoctor 1.6.0.

**Comment by obilodeau** [comment]
I'll use the second one and I don't see a problem with bumping the version and releasing if we are compatible.

**Comment by obilodeau** [comment]
Version 1.0.0 was released yesterday

**Comment by mojavelinux** [comment]
:tada: :beers:
