### ISSUE TITLE
Multiple authors not taken into consideration in revealjs output?

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-reveal.js#122]
asciidoc source:
(note the 2 authors)

https://raw.githubusercontent.com/seinecle/gephi-tutorials/master/src/main/asciidoc/en/plugins/twitter-streaming-importer-en.adoc

revelajs outpout:
(just one author appearing on the title page)

https://seinecle.github.io/gephi-tutorials/generated-slides/twitter-streaming-importer-en.html

**Comment by obilodeau** [comment]
Confirmed that multiple authors support is not present in the slim backend: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/slim/document.html.slim#L99

Author support is completely absent in the jade backend.

**Comment by obilodeau** [comment]
Jade back-end is no longer relevant in master. Removing label.

**Comment by marcotama** [comment]
I would love to see this fixed. Can I help? I have a general programming background, but I am not sure where to start.

**Comment by obilodeau** [comment]
Setup the Asciidoctor-revealjs plugin in development mode: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/HACKING.adoc#test-a-local-asciidoctor-revealjs-version-1

Modify the slim template here: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/document.html.slim#L106

Make sure you `bundle exec rake build` after making changes because we are using compiled slim templates now.

Relevant documentation to help you debug more: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/HACKING.adoc#inspect-the-template-system

This would be a great PR for a Hackertoberfest free t-shirt by the way, check if you haven't heard about it: https://hacktoberfest.digitalocean.com/

Ping me on https://gitter.im/asciidoctor/asciidoctor if you need interactive help. I'll try my best but can't guarantee availability.

**Comment by archiloque** [comment]
I noticed there even if multiple authors are not yet supported there is an error in the original Asciidoctor file, I've opened a separated PR at https://github.com/seinecle/gephi-tutorials/pull/28
