### ISSUE TITLE
How to overwrite reveal.js speaker notes CSS styles?

### ISSUE THREAD

**Issue by ehmkah** [asciidoctor/asciidoctor-reveal.js#137]
I need to fix the settings for the speaker-notes screen. For me a bigger notes section would be cool.

the following approaches are working but are overwritten which each build
- If I change the width of `#speaker-controls` css attribute in chrome 
- manipulate the notes.html file which is generated by maven

So how could I make this change persistent when the presentation is generated?

**Comment by obilodeau** [comment]
Have you tried using the latest version of reveal.js and the new speaker notes layout option? See a demo: https://cloud.githubusercontent.com/assets/629429/21808439/b941eb52-d743-11e6-9936-44ef80c60580.gif

If that's not enough, there's not much else you can do within asciidoc markup since the speaker notes page's CSS is all inline.

What I've done in the past is fork reveal.js, patch it and use my forked version for my presentations. This is the way I handle themes also.

**Comment by ehmkah** [comment]
@obilodeau  - Thank you. That is all I need. You saved my presentation for tomorrow.

**Comment by mojavelinux** [comment]
This video is excellent! I strongly encourage you to add it to the README so users don't miss this great feature.

**Comment by obilodeau** [comment]
Done
