### ISSUE TITLE
support for sections

### ISSUE THREAD

**Issue by GeraldLoeffler** [asciidoctor/asciidoctor-reveal.js#139]
The reveal.js backend seems to produce presentations that are basically flat, unstructured lists of slides (ignoring the "vertical slides" feature). It would be great if it supported sections, where the start of a section is a slide similar to a title slide, but in the middle of the presentation.

For instance, 
- the level-1 heading denotes the entire presentation and its title,
- level-2 headings could demarcate sections and their titles,
- and level-3 headings would then identify the individual slides and their titles within a section

**Comment by obilodeau** [comment]
Vertical slides are supported and documented in the README page: https://github.com/asciidoctor/asciidoctor-reveal.js#vertical-slides. It's done by using level-3 headings.

I accomplish what you call sections by using an attribute applied to slide sections.

The asciidoc attribute I create:
```
:topic: .topic,background-color="#df3e34"
```

The CSS I use:
```
.reveal section.topic h2 {
        margin-top: 2.5em;
        font-size: 3em;
}

.reveal section.has-dark-background h2,
.reveal section.has-dark-background h3,
.reveal section.has-dark-background p {
        color: white;
}
```

And in the slides:
```
== Agenda

* The Vision
* The Team
* ...

[{topic}]
== The Vision

== !

Being *visionnary*...

```

I don't see how we can provide a default that would please everyone because you can specify background image, color, slide transition and all sorts of different things. Using CSS and an attribute is a very flexible combination.

I think this is the way to go. We need to map as closely as possible to reveal.js' feature otherwise users will get confused.

That said if you would like us to provide shortcuts or predefined CSS to make that easier I would be open to that given that it is not intrusive and can expose most reveal.js' features that applies to slides.

**Comment by obilodeau** [comment]
Closing this. Feel free to re-open if you have ideas or suggestions.
