### ISSUE TITLE
slim directory not found

### ISSUE THREAD

**Issue by jagedn** [asciidoctor/asciidoctor-reveal.js#147]
I think after #143 slim files are in the _templates_ directory whereas previously was in _templates/slim_ subdirectory

I don't know if this is the right place but I was following https://github.com/asciidoctor/asciidoctor-gradle-examples/tree/master/asciidoc-to-revealjs-example and previously this change it was fine but today It started to fail

I changed my build.gradle from:

`options template_dirs: [new File(templateDir,'templates/slim').absolutePath]`

to

`options template_dirs: [new File(templateDir,'templates').absolutePath]`

and now It's working ok. 

If this is the right place from now, feel free to close this issue

**Comment by obilodeau** [comment]
I didn't realize that this repo hadn't switched to our packaged releases (since 1.0.0). Instead of pulling in `slim`, files directly from master and doing the conversion themselves, shouldn't they pull our ruby package? I guess opening an issue on that repo would be the way to move this into resolution.

**Comment by jagedn** [comment]
Thnks
