### ISSUE TITLE
Vertical slides not working

### ISSUE THREAD

**Issue by SevereOverfl0w** [asciidoctor/asciidoctor-reveal.js#155]
I'm using asciidoctor.js and asciidoctor-reveal.js 1.0.4

The vertical slides are shown below the `== Title` instead of as they're supposed to

![Example of invalid vertical slides](https://kek.gg/i/7qDHyH.png)

**Comment by obilodeau** [comment]
As you can see in #63, before we merged #131, we were using two sets of templates one for ruby (complete) and one for javascript (very incomplete).

With master now we compile the template into ruby which will then get converted to javascript. We haven't made a release because we are waiting on a bug with asciidoctor.js tracked here: #143.

If you can, I would advise that you use 1.0.4 from ruby instead of javascript.

**Comment by obilodeau** [comment]
Can you try again with the latest release? With 1.1.0 we are using the same templates from both ruby and javascript.

I will close this but feel free to re-open if it still doesn't work.
