### ISSUE TITLE
Templates location wrong in the documentation

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-reveal.js#157]
Hi,

Related to this issue https://github.com/asciidoctor/asciidoctor-maven-examples/issues/62, I saw that the templates location have changed and the `slim`, `jade` directories no longer exist in master branch.
However, the README still mentions them, is this a bug or documentation error?

thanks,

**Comment by obilodeau** [comment]
It's a documentation error. However, since we haven't released 1.1.0 which is the version that completely changes how we use the templates and we have no real homepage beside the GitHub's README then it's fair to point to the outdated information because this is what you would expect by using the ruby gem (at 1.0.4 now).

It should be noted that the maven plugin should probably use released versions (instead of master) and avoid using the slim templates directly because since [1.0.0](https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v1.0.0) we are a full ruby front-end to asciidoctor. In 1.0.x you could use the Javascript back-end also if that's preferable to Ruby/JRuby but the Jade templates are way behind the Slim ones (see #63).

With 1.1.0 the slim templates are compiled to Ruby and converted to Javascript via Opal. This makes our Ruby and Javascript back-end to have feature parity and we only need to maintain one set of templates. This will be released soon.

I would consider our "API" to be these front-ends since 1.0.0 and work hard to avoid breakage when slides are converted using these (as opposed to be afraid to rename template directories for example).

I'm going to update this ticket to track the documentation changes required when we release 1.1.0. Thanks for reporting it! Feel free to ask further questions and give suggestions, I didn't expect to have a _downstream_ so I'm sorry if I broke your stuff with my changes.

**Comment by obilodeau** [comment]
TODO
- [ ] README mentions of templates/{slim,jade}
- [ ] README section on Jade (should probably remove all of it to simplify docs)
- [ ] HACKING: get rid of jade specifics and explain back-end to make sure people understand what's going on

**Comment by abelsromero** [comment]
> since we haven't released 1.1.0 which is the version that completely changes how we use the templates and we have no real homepage beside the GitHub's README then it's fair to point to the outdated information because this is what you would expect by using the ruby gem (at 1.0.4 now)

In the maven plugin we adopted the way https://github.com/asciidoctor/jekyll-asciidoc/ does. We have a note at the start of the document pointing to the README of previous tags and explain that the user is seeing documentation for snapshot. Not perfect but helps.

> It should be noted that the maven plugin should probably use released versions (instead of master)

Agree, I'd propose a PR. But the impact is in an examples repo, not the actual plugin, so not a big thing. I suspect the example was created along time ago before official releases and that's why it uses master.

> Feel free to ask further questions and give suggestions,

You answered far ore than what I asked 👍 No more questions.
