### ISSUE TITLE
settomg data-fragment-index on elements

### ISSUE THREAD

**Issue by fiddlededee** [asciidoctor/asciidoctor-reveal.js#241]
It would be great to have possibility to set data-fragment-index on an element. This could allow to make simultaneous appearence or disappearence or whatever else of several elements.

This issue https://github.com/asciidoctor/asciidoctor/issues/1305 would solve the  problem, but it is not implemented yet.

General solution could look like:

[.fragment.highlight-red, data-fragment-index=1]#text1#
[.fragment.highlight-red, data-fragment-index=0]#text2#
[.fragment.highlight-red, data-fragment-index=1]#text3#

On the 1st step we get text2 turning red, on the second -- text1 and text3 turning red.

**Comment by obilodeau** [comment]
Interesting idea! I anticipate it would be straight forward to implement too.

We need to release 2.0 first so I'll tag it for 2.1. If someone PRs this before we release we will review and accept. Contributions welcome!

**Comment by mojavelinux** [comment]
FYI, solving https://github.com/asciidoctor/asciidoctor/issues/1305 wouldn't solve the problem for this converter since the implementation is specific to the converter. In other words, the reveal converter can implement passthrough support for data- attributes today without waiting for core. It's a converter concern. All user-defined attributes are available via the API.

**Comment by ebousse** [comment]
This feature would indeed be great! :)
