### ISSUE TITLE
Footnotes don't appear

### ISSUE THREAD

**Issue by wackywendell** [asciidoctor/asciidoctor-reveal.js#30]
Footnotes do not seem to appear:

``` asciidoc
= A Test Document
Author Name
:revealjs_theme: simple
:revealjs_transition: none
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.0.0/
:stem: latexmath
:imagesdir: imgs

== Test

This is some text with footnote:[An example footnote.]
```

The text of the footnote doesn't seem to show up in the HTML:

``` html
<section id="_test"><h2>Test</h2><div class="paragraph">
  <p>This is some text with 
    <span class="footnote">[<a id="_footnoteref_1" class="footnote" href="#_footnote_1" title="View footnote.">1</a>]</span>
  </p>
</div></section>
```

There's more HTML than that, of course, but nothing with the footnote text in it.

**Comment by mojavelinux** [comment]
Footnotes are not implemented in the reveal.js backend. But before we add them, we need to make a design decision. Where should the footnotes appear? Should they appear at the bottom of the slide from which they come? Should they appear on a references slide at the end of the presentation?

It is possible to check for new footnotes at the bottom of a slide and add them. The API is a little clunky, but I believe the necessary information is there.

**Comment by wackywendell** [comment]
Good questions / points. I assumed "footnote" would mean "bottom of slide", given that it normally means "bottom of page", but that is a design assumption...

**Comment by mojavelinux** [comment]
Let's start with the bottom of the slide.

**Comment by keithbuhler** [comment]
I'll add my vote to putting them on the bottom of the slide. For now, I'm just hyperlinking to references.

**Comment by obilodeau** [comment]
Another option to consider: https://github.com/e-gor/Reveal.js-Title-Footer

**Comment by lalebarde** [comment]
With Asciidoctor PDF 1.5.0.beta.1 using Asciidoctor 2.0.10, it goes to the last slide. Why not distinguishing:

- footnote : in the bottom of the slide

- endnote : in a slide declared as 'endnotes' receipient (not necessarily the last one)

**Comment by Ezwen** [comment]
This would be great to have! I tend to put references to other papers/works at the bottom of slides using footnotes.

**Comment by obilodeau** [comment]
I'll explore this for the next release

**Comment by Mogztter** [comment]
> Let's start with the bottom of the slide.

In this case, I think we should probably reset the numbering on each slide right?

| | |
| -- | -- |
|![localhost_63342_asciidoctor-reveal js_examples_footnotes html__ijt=tv4jdq6vih9uc9d3rkmklp8igd](https://user-images.githubusercontent.com/333276/100539590-d569c180-3237-11eb-80ff-42d73a47335e.png) | ![localhost_63342_asciidoctor-reveal js_examples_footnotes html__ijt=tv4jdq6vih9uc9d3rkmklp8igd (1)](https://user-images.githubusercontent.com/333276/100539589-d569c180-3237-11eb-869a-369edb8f2db9.png) |
| | ![localhost_63342_asciidoctor-reveal js_examples_footnotes html__ijt=tv4jdq6vih9uc9d3rkmklp8igd (2)](https://user-images.githubusercontent.com/333276/100539587-d4d12b00-3237-11eb-9603-d1bf8bf7096b.png) |

As you can see on the second slide, the footnotes numbering starts at 2... but it feels a bit weird no?

Also, I don't think that we need to generate a link, since the definitions/descriptions are on the same slide.

Of course, if we decide to put footnotes on a dedicated slide then it would be different.

**Comment by mojavelinux** [comment]
I agree if the footnotes go on the slide, the numbering should be reset (if possible).

Being able to put the footnotes on the final slide is an interesting idea. It would match the presentation pattern of putting credits on the last slide. So I think it would be worthwhile to explore.
