### ISSUE TITLE
Missing brand icons in v3.0

### ISSUE THREAD

**Issue by gquintana** [asciidoctor/asciidoctor-reveal.js#304]
Since I upgraded to ascidoctor-reveal.js from v2.0.1 (Font Awesome 4.7) to v3.0.0 (Font Awesome 5). I miss social network icons. All other icons are alright.

For example, the following is not rendered properly:
```
icon:twitter[] twitter
icon:github[] github
```
![Firefox_Screenshot_2020-01-11T16-32-24 051Z](https://user-images.githubusercontent.com/755587/72207332-7de42b00-3498-11ea-9085-d53ab2ad4ea3.png)
This kind of icon should be rendered as
```
<i class="fab fa-twitter"></i>
```
Not
```
<i class="fa fa-twitter"></i>
```
How can I do it?

**Comment by obilodeau** [comment]
I realize now that the problem is that we updated before asciidoctor started supporting it (see https://github.com/asciidoctor/asciidoctor/issues/2535). It's a pity that Font Awesome did a pretty breaking change.

I'll try the shim offered by Font Awesome and if that doesn't work I'll switch back to the latest Font Awesome 4

**Comment by obilodeau** [comment]
I can confirm that adding:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/v4-shims.min.css">
```

after

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css">
```

in the generated HTML file fixes the issue for twitter (and most likely others).

I'll do a PR soon and probably a release. In the meantime you can add it manually after the conversion.

I just read the Font-Awesome changelog and I'll update to 5.12.0 at the same time since there's nothing breaking and a bunch of new icons.

**Comment by Mogztter** [comment]
Currently, it's not possible because the template is always using `fa` as a CSS class:

https://github.com/asciidoctor/asciidoctor-reveal.js/blob/95fa8edd770f1733b9c9c02ce4ea64b3aab403df/templates/inline_image.html.slim#L3


In [Asciidoctor Web PDF](https://github.com/Mogztter/asciidoctor-pdf.js/blob/ee8efaee4df18be42485b4e3eb6eadc4ebffe0b6/lib/document/templates.js#L192), I've added an attribute named `set` to support multiple styles or icons libraries:

```
icon:address-book[] icon:address-book[set=far]
```

I've also added a concise syntax to define a set with the `@` symbol:

```
icon:chrome@fab[]
````

We should probably implement this feature in this project.
In your case, you will need to write:

```
icon:twitter@fab[]
```

And it will be converted to:

```html
<i class="fab fa-twitter"></i>
```

**Comment by obilodeau** [comment]
Yes, it's going to be shim for now and wait for upstream asciidoctor support. I don't want to follow a syntax that I'm not sure is going to go upstream in asciidoctor.

**Comment by gquintana** [comment]
Thanks for the fix

**Comment by mrcasablr** [comment]
@Mogztter @obilodeau None of the following work for me in 4.0.1

icon:jira@fab[]
icon:jira[]
icon:atlassian@fab[]
icon:atlassian[]

**Comment by Mogztter** [comment]
Indeed it does not work with new icons (introduced in Font Awesome 5) because we do not use the new `fab` prefix:

https://github.com/asciidoctor/asciidoctor-reveal.js/blob/2eb03a514a9eab017ecaf6ac55103ea896fb759d/templates/inline_image.html.slim#L3

I think we should implement the "set" feature described here: https://github.com/asciidoctor/asciidoctor-reveal.js/issues/304#issuecomment-573359189

@mrcasablr Could you please open a new issue so we can work on it?
