### ISSUE TITLE
section id starting with underscore breaks starting from specific slide in url

### ISSUE THREAD

**Issue by bartoleo** [asciidoctor/asciidoctor-reveal.js#32]
reveal.js on page open checks if url contains a slide 'id' as hash (function readURL())
sections generated by asciidoctor-reveal have id starting with underscore 
reveal.js checks if the id found is valid
```
// Ensure the named link is a valid HTML ID attribute
			if( /^[a-zA-Z][\w:.-]*$/.test( name ) ) {
```
and it's always Not valid so it starts from beginning

I made a workaround in /asciidoctor-reveal.js/templates/slim/section.html.slim, adding 'slide' before id:
 'slide'+@id

**Comment by mojavelinux** [comment]
I've noticed this as well.

I think this simply needs to be documented. You must set the `idprefix` in your AsciiDoc document.

```
= Presentation Title
:idprefix:
```

or

```
= Presentation Title
:idprefix: slide_
```

We could see if it's possible to set a better default from the converter to save you the trouble.

**Comment by bartoleo** [comment]
perfect, thank you!!!

I have still a problem with id containing accented letters like à è ì ò ù (and uppercase version)
reveal.js during url writing strips these characters

I made another workaround in /asciidoctor-reveal.js/templates/slim/section.html.slim, replacing characters in id:
```
@id.gsub(/[^a-zA-Z0-9\-\_\:\.]/, '')
```

**Comment by mojavelinux** [comment]
That's a reasonable workaround to consider adding to this backend.

I think the real problem here is the logic in reveal.js. Asciidoctor purposefully permits all characters that are allowed by the HTML spec. reveal.js is being overly conservative by stripping these. `à` is a perfectly valid letter character and reveal.js is showing its bias towards English by stripping it.

Having said that, I'm still prepared to do what we have to do to make it work (esp if reveal.js refuses to change). Keep in mind that we'll need to think about references to those ids (i.e., inline_anchor), though in a presentation that's less critical.

**Comment by bartoleo** [comment]
I'll open an Issue on reveal.js asking to remove this constraints

**Comment by mojavelinux** [comment]
Thanks!

**Comment by bartoleo** [comment]
opened:
https://github.com/hakimel/reveal.js/issues/1230

**Comment by obilodeau** [comment]
Fixed. See #75.

**Comment by mojavelinux** [comment]
@obilodeau Can you add a comment in the source code that the workaround is temporary. In the long run, we don't want to be manipulating the ID that Asciidoctor generates as it can break xrefs.
