### ISSUE TITLE
Can templates be overridden with the standalone CLI?

### ISSUE THREAD

**Issue by darinpope** [asciidoctor/asciidoctor-reveal.js#349]
Based on the enhancement list from 4.0.0:

> Built-in slim templates can now be overridden with --template-dir or -T

I'm not seeing that it is working with the standalone macOS version:

> asciidoctor-revealjs --version
> Asciidoctor reveal.js 4.0.1 using Asciidoctor.js 2.1.1 (Asciidoctor 2.0.10) [https://asciidoctor.org]
> Runtime Environment (node v12.13.1 on darwin)

I did see in one of the related issues that it might only apply to Ruby and not the other flavors/distros. 

Should template override work with the standalones?

**Comment by obilodeau** [comment]
`--template-dir` is only available using the Ruby platform. I realize that documentation is lacking in that regard. I'll update it. The related issue you were talking about is #177.

@Mogztter do you think something can be done for the asciidoctor.js side (w/ standalone being supported as well as a bonus)? It could be pug templating instead of tilt/slim. I believe that would be easier. Is this PR (https://github.com/asciidoctor/asciidoctor.js/pull/770) helping in any way or it would need to be an unrelated implementation?

**Comment by Mogztter** [comment]
> --template-dir is only available using the Ruby platform. I realize that documentation is lacking in that regard. I'll update it. The related issue you were talking about is #177.

Indeed, Asciidoctor.js does not (yet) have a template converter.

> do you think something can be done for the asciidoctor.js side (w/ standalone being supported as well as a bonus)? It could be pug templating instead of tilt/slim. I believe that would be easier. Is this PR (asciidoctor/asciidoctor.js#770) helping in any way or it would need to be an unrelated implementation?

Yes asciidoctor/asciidoctor.js#770 is related. It will probably be included in Asciidoctor.js 2.2.0. 
I also have a prototype where I'm using ERB templates (compiled to JavaScript using Opal) but it won't work with Tilt/Slim templates (I mean, in theory, it could but I don't want to spend time cross-compiling Slim to JavaScript)

**Comment by obilodeau** [comment]
* Updated release notes on GitHub for 4.0.0
* Submitted PR #351
