### ISSUE TITLE
Squelch html5 nag message.

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor-reveal.js#36]
Not sure if it is a nag message or something that should be addressed. Not sure whether the bug in the unpublished README is what is causing this.

[jmorgan@localhost Asciidoctor_Presentation]$ asciidoctor -T ../asciidoctor-reveal.js/templates/slim Asciidoctor_Tech_Demo_Slides.adoc 
Format :html5 is deprecated, use :html
Format :html5 is deprecated, use :html
Format :html5 is deprecated, use :html
Format :html5 is deprecated, use :html
Format :html5 is deprecated, use :html
Format :html5 is deprecated, use :html
Format :html5 is deprecated, use :html
Format :html5 is deprecated, use :html
Format :html5 is deprecated, use :html

For the record, the presentation builds from https://github.com/jaredmorgs/Asciidoctor_Presentation so it can't be that bad.

I think that if I'm planning on showing folks how to make slides from .adoc, this might freak out some new folks. ;)

**Comment by mojavelinux** [comment]
This message is actually coming from a separate gem, Slim. The Slim 3.0.0 gem made an incompatible change (it changed the name of the HTML format). As a result, the option that Asciidoctor has always passed to Slim now triggers this warning. This problem has been fixed in the upcoming Asciidoctor 1.5.3 (https://github.com/asciidoctor/asciidoctor/commit/1a1a23450b64306be18a83d9d78a8c3d7a2bfb54). 

A quick fix for this problem in the interim is to use Slim 2.1.0 instead of Slim 3.0.x. Unfortunately, there's little we can do (I'm not ruling out the possibility of discovering a clever workaround) to silence this error when using Asciidoctor 1.5.2 with Slim 3.0.x.

**Comment by mojavelinux** [comment]
I think we should update the README to recommend sticking with Slim 2.1 when using Asciidoctor 1.5.2.

**Comment by mojavelinux** [comment]
Actually, the README does recommend using Slim 2.1 already. However, it doesn't explain this issue in particular.

**Comment by jaredmorgs** [comment]
Has 1.5.3 been released yet (sorry, lost track of numbers). If not, I'll doc this issue directly in the README.

**Comment by mojavelinux** [comment]
1.5.3 isn't out yet, but I'm starting to focus on making it happen. It will probably be a few weeks still before it's ready. (See https://github.com/asciidoctor/asciidoctor/milestones/v1.5.3)

**Comment by obilodeau** [comment]
This is no longer relevant. The back-end requires 1.5.4 which, I believe, works around the slim version issue.

**Comment by mojavelinux** [comment]
Correct.
