### ISSUE TITLE
reveal.js 4.0 support

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#370]
4.0.0 was [released](https://github.com/hakimel/reveal.js/releases/tag/4.0.0) last week and with it enough breaking changes for us to mandate another breaking one.

However, one thing we will need to do in the meantime is to change all of our links to the reveal.js README to point to their new 3.9 branch. They released a dedicated documentation site and stripped their README of all the stuff. I think master and maybe -1, -2 major releases should point to the right location (given it's only some vim regex wizardry at this point) and adjust all the links for our next major release.

**Comment by gautaz** [comment]
Hello,

[Reveal.js 4.1.0 was since released](https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v4.1.0) and it notably fixes the autoplay feature which no longer works on both youtube and vimeo.

No hurry, this is just a follow up for this issue :-).

**Comment by Mogztter** [comment]
Hi!

I think you meant to link: https://github.com/hakimel/reveal.js/releases/tag/4.1.0 right?

> and it notably fixes the autoplay feature which no longer works on both youtube and vimeo.

I'm not sure if I follow... could you please explain again?
For reference, Asciidoctor reveal.js 4.1.0 is using reveal.js 3.9.2. As far as I know, Asciidoctor reveal.js 4.1.0 is not compatible with reveal.js 4+.

**Comment by obilodeau** [comment]
[Compatibility matrix](https://github.com/asciidoctor/asciidoctor-reveal.js#revealjs-compatibility-matrix) should make this clearer. Reveal.js 4.x is not supported right now.

![image](https://user-images.githubusercontent.com/546325/106002131-c019e380-607e-11eb-9d11-b275cfa07c06.png)

**Comment by Mogztter** [comment]
> Compatibility matrix should make this clearer. Reveal.js 4.x is not supported right now.

It would be a bit odd to add a row in the compatiblity matrix no?

|Asciidoctor reveal.js version|reveal.js version|
| -- | -- |
| No compatible release (yet) | >= 4.0 |
| 4.x | 3.9 - 3.8
|3.x, 2.x, 1.x | 3.7-3.0
|Unversioned releases | 2.x 

Instead, we could probably add a NOTE to state that reveal.js 4.x is not yet supported?

**Comment by gautaz** [comment]
> I think you meant to link: https://github.com/hakimel/reveal.js/releases/tag/4.1.0 right?
> 
> > and it notably fixes the autoplay feature which no longer works on both youtube and vimeo.
> 
> I'm not sure if I follow... could you please explain again?
> For reference, Asciidoctor reveal.js 4.1.0 is using reveal.js 3.9.2. As far as I know, Asciidoctor reveal.js 4.1.0 is not compatible with reveal.js 4+.

@Mogztter Oops! You're right, I have mixed up the release notes.
I stumbled upon these while trying to understand why autoplay is not currently working with asciidoctor-revealjs while using revealjs 3.9.2 (I'm using the latest docker container image from the docker hub: asciidoctor/docker-asciidoctor).
Sorry for interfering with this issue...

**Comment by edl7878** [comment]
According to reveal.js 4.x upgrading document:
https://revealjs.com/upgrading/

It is just some asset file pathes are changed. Is it possible to issue a new asciidoctor-reveal.js for the 4.0.x of reveal.js?

**Comment by Mogztter** [comment]
I haven't had the time to look at it closely but, since this issue is labeled as "help wanted", feel free to submit a pull request, I will gladly review it.

I can also assist if you need help to get started 🤗

**Comment by edl7878** [comment]
On windows10, following the doc:
https://docs.asciidoctor.org/reveal.js-converter/latest/project/hacking/

when run: bundle exec rake build

an error occurred: `The git source https://github.com/opal/opal.git is not yet checked out. Please run `bundle install` before trying to start your application`

gem 3.2.15
ruby 3.0.1p64

**Comment by Mogztter** [comment]
Thanks for raising this issue.
I'm not sure why but some important steps are missing from the hacking/contributing guide. Maybe we forgot to add them because they are described somewhere else or maybe just an overlook.

Anyway, I think we need to add prerequisites in the contributing guide:

- Recommend to install/use rvm (optional)
- Install Ruby version x.y.z
- Install git
- Recommend to install/use nvm (optional)
- Install Node version x.y.z
- Install Ruby dependencies: `bundle install`
- Install JavaScript dependencies: `npm i`

We are testing against Windows using GitHub Actions and it seems to work.

I think the root cause is:

```
Errno::EACCES: Permission denied @ rb_file_s_symlink - (bin/ruby-beautify,
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ruby-beautify2-0.98.0/bin/rbeautify)
```

I would recommend to use rvm to install gem dependencies in the user space.
If it does not work we should probably report this issue at: https://github.com/jirutka/ruby-beautify2

**Comment by Mogztter** [comment]
Alternatively, I think you can use `bundle --path=.bundle/gems --binstubs=.bundle/.bin`. It should install dependencies locally (inside the project directory).

**Comment by Mogztter** [comment]
We should probably take inspiration from https://github.com/asciidoctor/asciidoctor/blob/master/CONTRIBUTING.adoc#submitting-a-pull-request

**Comment by edl7878** [comment]
I have made a pull request:
https://github.com/asciidoctor/asciidoctor-reveal.js/pull/427

basd on my test, new layout of reveal.js is workable, such as `r-fit-text`.

![image](https://user-images.githubusercontent.com/1988479/120937982-27d5ee80-c743-11eb-8184-cde92ce5c492.png)

**Comment by Mogztter** [comment]
Thanks, I will review it this week.

> Since old code base default revealjsdir is node_modules/reveal.js, I havn't modified this default value, which means users would have to define :revealjsdir: in their adocs explicitly for now.

The default value is `node_modules/reveal.js` when using Asciidoctor.js (JavaScript). As far as I understand, this is default value is still valid with reveal.js 4.x no?
When using Asciidoctor (Ruby) the default value is `reveal.js`.

**Comment by edl7878** [comment]
As user git clone reveal.js 4.x the folder structure likes below:
![image](https://user-images.githubusercontent.com/1988479/120967595-40252800-c79a-11eb-9bd7-54583eaf482c.png)
reveal.js is under dist folder,  it is documented by reveal.js in:
https://revealjs.com/upgrading/

I don't know why the default :revealjsdir: value is varied between asciidoctor.js and Asciidoctor(Ruby).

I think when converting  adoc to html, if reveal.js is not needed, for asciidoctor.js, the default value of :revealjsdir: can be reveal.js too.  So that for both Asciidoctor and Asciidoctor.js the default values are the same.

**Comment by edl7878** [comment]
OK，got it， thanks.
