### ISSUE TITLE
math plugin

### ISSUE THREAD

**Issue by andreabedini** [asciidoctor/asciidoctor-reveal.js#4]
Reveal.js has a [math plugin](https://github.com/hakimel/reveal.js/issues/531) but it seems there's no way to enable it from the template.

PS: Amazing work guys!

**Comment by mojavelinux** [comment]
You should enable math the same way you do in a normal AsciiDoc document, by setting the `stem` attribute.

```
= Presentation
:stem: latexmath

== Math

[stem]
++++
(a + b)^2 = a^2 + 2ab + b^2
++++
```

Then, we automatically add the necessary MathJax script. We must do this manual instead of using the reveal.js plugin because we use custom delimiters. Try it out and see if it works for you. If so, we'll close the issue.

**Comment by andreabedini** [comment]
works wonderfully, thanks @mojavelinux

**Comment by mojavelinux** [comment]
Excellent!
