### ISSUE TITLE
Expanded fragment support

### ISSUE THREAD

**Issue by craigburke** [asciidoctor/asciidoctor-reveal.js#41]
Would be nice to have fragment support for sections other than lists (like code blocks or text).

Basically would be good to be able to recreate this slide:
http://lab.hakim.se/reveal-js/#/fragments

**Comment by mojavelinux** [comment]
Technically, you can already do this for many elements. You just have to add the "fragment" role to the AsciiDoc block or inline element. That translates into a reveal.js fragment.

```
Hello, World! +
[fragment]#Goodbye, World.#
```

Ideally, though, we'd map the step role or option to the fragment role to keep it agnostic to framework terminology.

```
Hello, World! +
[step]#Goodbye, World.#
```

(options don't get applied to inline formatting marks, which is why we must use a role).

**Comment by craigburke** [comment]
Ok, I didn't know about the fragment role. That's extremely helpful. Thank you!
