### ISSUE TITLE
Subscripts are outputted as superscripts

### ISSUE THREAD

**Issue by 9ao9ai9ar** [asciidoctor/asciidoctor-reveal.js#415]
The bug seems to be introduced in a3a13667222839e784fbdde8988e1833df951d05.

Outputs are fine if using the HTML backend.

**Comment by Mogztter** [comment]
Nice catch!
The issue was indeed introduced in a3a1366.

The faulty line: 

https://github.com/asciidoctor/asciidoctor-reveal.js/blob/b82f0ca6b413f00158c9a6be31b32559e2b68bdd/templates/inline_quoted.html.slim#L1

It should be:

```slim
 - quote_tags = { emphasis: 'em', strong: 'strong', monospaced: 'code', superscript: 'sup', subscript: 'sub' } 
```

(notice the last part, `subscript: 'sub'`)

Feel free to open a pull request to fix this issue.
