### ISSUE TITLE
Support auto-animate

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-reveal.js#423]
I would love to use [animating between source code blocks](https://revealjs.com/auto-animate/#example%3A-animating-between-code-blocks)

There seem to be 3 conditions needed to make this work:

1. Add `data-auto-animate` to the `<section>` element
2. Set a `data-id` value for the code blocks that need to animate together
3. Add `data-line-numbers` to the `<code>` element

Point 3 can be done by adding `linenums`:

```
[source,java,linenums]
----
public class TestClass {
}
----
```

I have not found how I can do points 1 & 2.

I tried to use `data-auto-animate` on the slide titles like this:

```
[data-auto-animate=true]
== My Slide Title 

[source,java,linenums]
----
public class TestClass {
}
----
```

But that did not seem to work.

I tried with `[data-auto-animate]` and `[data-auto-animate=]` as well (Inspired by https://www.gijsvandam.nl/posts/pandoc-revealjs-animation/)

Am I missing something, or will a change be required to make it work?

**Comment by g4gilson** [comment]
Maybe `[role="data-auto-animate"]` or `[.data-auto-animate]` will do the job.
To have some data attribute example, maybe this example will help you:
https://github.com/asciidoctor/asciidoctor-reveal.js/blob/1bc53e50b6bbee977732e7f2ecf507cb599ba556/examples/data-attributes.adoc

**Comment by Mogztter** [comment]
I didn't add support for data attributes on `<section>` because `data-*` attributes are inferred from AsciiDoc attributes: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/4a29cb71182cb4f51a48eee8ade62e801b63f32a/templates/section.html.slim#L50-L66

@wimdeblauwe Feel free to open a pull request to add:

```slim
data-auto-animate=(attr "auto-animate") 
```

In the future, we could add data attributes support and consider removing/deprecating AsciiDoc attributes (i.e., `[background-color="yellow"]` -> `[data-background-color="yellow"]`):


```slim
= html_tag('section', { :id => (titleless ? nil : id, :class => roles }.merge(data_attrs(@attributes)))
```

**Comment by Mogztter** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor-reveal.js/pull/439
