### ISSUE TITLE
info on how to actually try out 5.0.0.-rc.1 ?

### ISSUE THREAD

**Issue by maxandersen** [asciidoctor/asciidoctor-reveal.js#468]
seeing https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v5.0.0-rc.1

but trying:

```
gem 'asciidoctor-revealjs', '5.0.0-rc.1' # latest released version
```

doesn't work.

Any other way?

**Comment by Mogztter** [comment]
Ruby gems is almost using semantic versioning 😅 
The version is `5.0.0.rc1`: https://rubygems.org/gems/asciidoctor-revealjs/versions/5.0.0.rc1. Since this is a pre-release you might need to add `--pre` if you do `gem install`:


```
$ gem install asciidoctor-revealjs -v 5.0.0.rc1 --pre
```

If you have additional questions feel free to join and ask in the community chat at [asciidoctor.zulipchat.com](https://asciidoctor.zulipchat.com/).

**Comment by mojavelinux** [comment]
@Mogztter I found a way to get Bundler and the gem command to honor the hyphen in prerelease versions. You can find what I did in asciidoctor-reducer.

* https://github.com/asciidoctor/asciidoctor-reducer/blob/main/gem-version-patch.rb
* https://github.com/asciidoctor/asciidoctor-reducer/blob/main/Rakefile#L3

Note that this does not affect users. By default `Gem::Version.new` just mangles the prerelease version if it contains a hyphen, which impacts `gem build` and thus the version that gets published.

I'm going to be using that moving forward in other projects in Asciidoctor. That should hopefully avoid this confusion.

**Comment by maxandersen** [comment]
thanks - with tthat I figured out the command to use in Gemfile is:

```
gem 'asciidoctor-revealjs', '>= 5.0.0.rc1'
```

the >= is needed to get it to install pre versions.

found other issue around highlightjs but asking that in #users on zulip.
