### ISSUE TITLE
cdn cannot be used anymore

### ISSUE THREAD

**Issue by hans-d** [asciidoctor/asciidoctor-reveal.js#485]
With https://github.com/asciidoctor/asciidoctor-reveal.js/pull/427, there is now a hardcoded path for /dist for both the script and the css.
When using `:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.2` this breaks.

**Comment by toastal** [comment]
When this bug is tackled, it should be known that there are [good reasons](https://httptoolkit.com/blog/public-cdn-risks/) to push for self-hosting Reveal.js over using a CDN for user security/privacy. At a bare minimum, a [subresource integrity hash](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) should be required like `:revealjs-integrity:`--and with the attribute missing, the document should fail to build with the CDN option.

**Comment by Mogztter** [comment]
We are moving away from cdnjs to jsdelivr.com

The following should work:
```
revealjsdir: https://cdn.jsdelivr.net/npm/reveal.js@4.1.2
```

I agree with @toastal using a self-hosted version is probably safer and it allows to build/preview a presentation offline which is reassuring especially with flaky Internet connection at conferences.
