### ISSUE TITLE
Table frame options and compact tables

### ISSUE THREAD

**Issue by anandchida** [asciidoctor/asciidoctor-reveal.js#56]
RevealJS backend by asciidoctor has been fantastic and has saved me a lot of time and has built impressive presentations. It was all so easy.

I'm trying to get tables right in my presentation and have the following issues -
1. Tables do not honor the frame="topbot" or all, or none attributes. Same applies for grid
2. I wanted table cells to be compact to fit more data.  I can fit 6 rows while 8 could be possible if cell height is reduced. Is there way to reduce cell height? I remember being a "compact" option for PDF backend I think. Any help is appreciated.

**Comment by mojavelinux** [comment]
That's great to hear!

We need to incorporate custom CSS in the backend that supplements the reveal.js theme. AsciiDoc content, like tables, requires additional CSS that is not going to be provided by the out-of-the-box reveal.js themes. Of course, you can supply your own custom CSS, or use docinfo to add additional CSS, but what we really should have is a CSS file that covers most of the common AsciiDoc styling and gets included into every presentation.

**Comment by obilodeau** [comment]
We just merged the support for frame and grid table attributes. This will be released in the upcoming 3.0.0. 

However, there is no compact option in upstream AsciiDoc tables. If you can provide an example we could develop custom CSS for it. Since this issue has been opened for a while I'm going to close it but if you are still interested in "compact", open a new issue and provide a syntax example and optionally CSS to achieve it.
