### ISSUE TITLE
Question: one slide for each title

### ISSUE THREAD

**Issue by archiloque** [asciidoctor/asciidoctor-reveal.js#59]
I want to use the reveal.js export for asciidoctor but I have an problem and don't see how to do it :
I want to write a presentation that use many titles levels and would like each title to be on it's own slide :

```
== A title : should be one slide
=== A subtile : should be on it's own slide
==== A sub-subtile : should be on it's own slide
```

The titles levels enable to keep the structure clean when editing the content and when doing an export in a single page.

From what I understand, I should modify section.html.slim file but I don't understand what I should change, and I think you could answer me in a few seconds :-)

If you're think this feature would be uselful to others I can probably create a PR about it with a switch.

**Comment by obilodeau** [comment]
Second level (`===`) are reserved for vertical slides. Third level and more are now supported starting with: https://github.com/asciidoctor/asciidoctor-reveal.js/commit/f027d08cd22a5e1ca27a46b96dd380abe062ba0a which was committed in March. They don't get their own slides, they just show up in the slides as `<h3>`, `<h4>`, etc.

Now that the handling of titles is consistent. I think the flexibility of having the ability to introduce `<h3>`, <h4>` in slides outweigh the gain in structure to have any level create a slide. What do you think?

**Comment by obilodeau** [comment]
I'm going to close this one. The ideas are worth exploring so if you are still interested, feel free to re-open.

**Comment by vivien** [comment]
Please re-open this issue. This is a strong limitation for writing backend-agnostic documents. It forces you to organize your document so that subtitles don't go deeper than h3. Sure h4 and below are supported, but having them within the same slide rarely makes sense in my opinion.

Using `ifdef::backend-revealjs[=== !]` is only a temporary solution for splitting long slides. Here's an illustration of the problem, considering a document meant for both a PDF article and a Reveal.js presentation:

````asciidoc
= Version Control Systems

Let's compare differents SCM solutions.

== SVN

=== Checkout

blah blah.

== Git

=== Clone

ifdef::backend-revealjs[:leveloffset: -1]
==== Bare
ifdef::backend-revealjs[:leveloffset: +1]

This clones only the $GIT_DIR, without checkout.

Some text.

ifdef::backend-revealjs[:leveloffset: -2]
===== Exercice
ifdef::backend-revealjs[:leveloffset: +2]

Do this.

And that.

And also that.

ifdef::backend-revealjs[:leveloffset: -1]
==== Depth
ifdef::backend-revealjs[:leveloffset: +1]

This clones a shallow copy with a truncated history.

== Conclusion

CVS is the best.
````

Still this is a cheap solution, because it prevents us from styling levels below h3, which will give no clue to the reader that we are in a subsection.

Pandoc has an option called [`--slide-level`](https://pandoc.org/MANUAL.html#structuring-the-slide-show) which might be a solution, but I think considering any heading as a new slide *by default* would be more intuitive for the writer.

In the meantime, thanks for your great work on this converter, it has just proven itself during a one-day training!

**Comment by mojavelinux** [comment]
Perhaps considering having a "flat" setting on the document which instead of creating vertical slides, just creates a linear presentation using section titles to a configurable depth.

I would find this interesting as I consider vertical slides to be a presentation anti-pattern.

**Comment by vivien** [comment]
For vertical slides, I suggest a `:vertical-slide-level:` attribute defaulting to 2, that one can disable with 0. Headings below the given value are vertical.

For the original issue with headings I suggest a `:slide-level:` attribute defaulting to 3 (in respect to the current behavior), that one can disable with 0. Headings below the given value are included in the current slide, 0 put every heading on its own slide.

But again, I hardly see how this can be a feature to someone. If we do need this to be configurable, I'd default `:slide-level:` to 0.
