### ISSUE TITLE
[Question] Pagebreak within a unordered list

### ISSUE THREAD

**Issue by danielgrycman** [asciidoctor/asciidoctor-reveal.js#60]
I have a long running unordered list and I want to split this list over two slides. The pagebreak (<<<) didn't work. Any ideas?

**Comment by mojavelinux** [comment]
I strongly recommend making two separate slides. I've reversed my stance on the use of pagebreak in the deck.js backend (and all slide backends for that matter) because it compromises the document structure. It's best to delineate slides using sections.

**Comment by danielgrycman** [comment]
@mojavelinux Thanks for the quick answer.

**Comment by mojavelinux** [comment]
Now that I think about it a bit more, there is one possibility where the page break would work here without breaking the documentation structure.

When processing the section, we could look for a page break in the content. If we find one, we'd create two slides instead of one, both with the same title...the content before the page break on the first slide and the content after the page break on the second.

Essentially, this:

```
== Title

* item
* item
* item

<<<

* item
* item
* item
```

is a shorthand for

```
== Title

* item
* item
* item

== Title

* item
* item
* item
```

Note that this is a very different use case for page break than using it to delineate slides (which I've seen done in some slide backends). Here, we are saying that we have one slide, but we want to split it up when displaying it.

I'm going to consider adding this to the Bespoke converter (where my effort is at the moment).
